#!/usr/bin/env bash
# Lists all running processes with specific columns: USER, STARTED, COMMAND

ps -eo user,lstart,cmd --no-headers | awk '{print $1, $2" "$3" "$4" "$5" "$6, substr($0, index($0,$7))}'

