#!/usr/bin/env bash
# A script that traps SIGTERM and prints a message instead of stopping

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done

